name: Tests

on:
  push:

jobs:
  test-docker-compose-whoami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./docker-compose/whoami && make test
  test-docker-compose-whoamitcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./docker-compose/whoamitcp && make test
  test-kubernetes-ingress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing k4d
        run: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v3.4.0 bash
      - run: cd ./kubernetes/ingress && make test
